# try-except 블록이란 무엇인가요?
---
간혹, 우발적이든 의도적이든, 당신이 적은 코드가 실패합니다. 그것은 우리가 에러나,  `예외` 라고 부르는걸 발생시킵니다. 파이썬은 일반적으로 실패했다는 메시지를 생성합니다. 떄로 우리는 코드 중지를 피하거나, 오류의 원인을 추적하려고 합니다. 이를 위해, 우리는  `try-except` 블록을 사용합니다. 그걸 우리가 사용할 수 있는 4가지의 다른 방법이 있습니다:

- `try` - 이건 try-except 블록의 시작으로, 블록이 어떤 예외든 던지는지를 효과적으로 테스트합니다.
- `except` - try블록에서 예외가 발생한다면, 이 블록이 실행됩니다. 그러나, 우리는 여러 유형의 예외를 사용통해 이들 중 다수를 지정할 수 있습니다.(아래 예시 보세요)
- `finally` - 이 코드블록은 코드의 성공하든 실패하든 상관없이 실행될것입니다.
- `else` - 당신은 오류가 발생하지 않으면 이 블록을 사용하여 코드실행을 정의할 수 있습니다.

만약 당신이 의도적으로 자신의 의지로 예외를 던지기를 원한다면, 파이썬도 그걸 허용합니다! 그것은 `raise.` 을 사용하여 달성할 수 있습니다.

#### 예시들:
---
```
def foo(bar): # 먼저 함수를 정의합니다.
	try:
		# 주장 진술은 보이는 그대로다. 
		# 그들은 주장 테스트에 있는 코드가 사실이라고 주장한다. 
		# 그렇지 않으면 주장 오류를 던진다.
		assert type(bar)==str
		if bar!="hello":
			raise Exception("hello world를 완수하지 못했습니다!") # 우리만의 예외를 던지기
	except AssertionError:
		print("bar 은 문자열이 아닙니다!")
	except Exception as e:
		print(e)
		print("또다른 예외가 발생했습니다!")
	else:
		print(bar+" world!")
	finally:
		print("프로그램 실행됨.")
```

```
>>> foo(1)
bar 은 문자열이 아닙니다!
프로그램 실행됨.

>>> foo("meow")
hello world를 완수하지 못했습니다!
또다른 예외가 발생했습니다!
프로그램 실행됨.

>>> foo("hello")
hello world!
프로그램 실행됨.
```